def generate_html_report_from_result(result: dict, output_file: str = "detailed_report.html"):
    meets_quality_gate = (
        result["enough_tests_run"] and
        result["high_pass_rate"] and
        result["acceptable_duration"] and
        result["no_critical_failures"]
    )

    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Test Quality Report</title>
        <style>
            body {{
                font-family: 'Segoe UI', sans-serif;
                background-color: #f0f4f8;
                padding: 20px;
                color: #333;
            }}
            .container {{
                max-width: 700px;
                margin: auto;
                background: white;
                padding: 30px;
                border-radius: 10px;
                box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            }}
            h1 {{
                text-align: center;
                color: #2c3e50;
            }}
            .section {{
                margin-top: 20px;
            }}
            .item {{
                display: flex;
                justify-content: space-between;
                margin: 8px 0;
            }}
            .highlight {{
                padding: 10px;
                margin-top: 20px;
                border-radius: 5px;
                font-weight: bold;
                text-align: center;
                color: white;
                background-color: {"#2ecc71" if meets_quality_gate else "#e74c3c"};
            }}
            .note {{
                font-size: 0.9em;
                color: #888;
                text-align: center;
                margin-top: 10px;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Test Execution Summary</h1>
            
            <div class="section">
                <div class="item"><span>Total Tests:</span><span>{result['total_tests']}</span></div>
                <div class="item"><span>Passed:</span><span>{result['passed_tests']}</span></div>
                <div class="item"><span>Failed:</span><span>{result['failed_tests']}</span></div>
                <div class="item"><span>Critical Failures:</span><span>{result['critical_failures']}</span></div>
                <div class="item"><span>Duration:</span><span>{result['duration_seconds']:.1f} sec</span></div>
                <div class="item"><span>Average Time/Test:</span><span>{result['avg_time_per_test']:.2f} sec</span></div>
                <div class="item"><span>Pass Rate:</span><span>{result['pass_rate']:.1f}%</span></div>
                <div class="item"><span>Release Candidate:</span><span>{"Yes" if result['is_release_candidate'] else "No"}</span></div>
            </div>

            <div class="section">
                <h2>Quality Gate Checks</h2>
                <div class="item"><span>Enough Tests Run (≥10):</span><span>{'✔️' if result['enough_tests_run'] else '❌'}</span></div>
                <div class="item"><span>High Pass Rate (&gt;90%):</span><span>{'✔️' if result['high_pass_rate'] else '❌'}</span></div>
                <div class="item"><span>Acceptable Avg Time/Test (≤10s):</span><span>{'✔️' if result['acceptable_duration'] else '❌'}</span></div>
                <div class="item"><span>No Critical Failures:</span><span>{'✔️' if result['no_critical_failures'] else '❌'}</span></div>
            </div>

            <div class="highlight">
                {"✅ Quality Gate PASSED" if meets_quality_gate else "❌ Quality Gate FAILED"}
            </div>

            <div class="note">Generated by Python</div>
        </div>
    </body>
    </html>
    """

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html_template)
    print(f"HTML report written to {output_file}")
